[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "drift-monitor-bhaskar"
version = "0.1.0"
description = "A Python library for ML data drift and data quality monitoring"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}

dependencies = [
    "pandas",
    "numpy",
    "scipy"
]

[project.scripts]
drift-monitor = "drift_monitor.cli:main"